google=https://www.google.com/

# Naukri login configuration
naukri.login.url=https://www.naukri.com/
naukri.user=shivamparashar1213@gmail.com
naukri.password=shivam1213

naukri.test=https://www.naukri.com/job-listings-ai-automation-engineer-makcliff-mysuru-2-to-6-years-240326035968?src=sortby&sid=17743614023367003_3&xp=1&px=1&nignbevent_src=jobsearchDeskGNB