#================== XPath ====================
# LogIn
loginLink=//a[text()='Login' or @id='login_Layer']
emailLocator=//label[text()='Email ID / Username']/following-sibling::input
passLocator=//label[text()='Password']/following-sibling::input
submitLogin=//button[text()='Login' or @type='submit']

# ChatBot
manual=//span[contains(text(),'willing to relocate')]/ancestor::ul/following-sibling::div//input[@value='Yes']
notice=//span[contains(text(),'Notice Period')]/ancestor::ul/following-sibling::div//div[@class='textArea']
noticeCheckBox=//label[text()='15 Days or less']/preceding-sibling::input
automation=//span[contains(text(),'Automation')]/ancestor::ul/following-sibling::div//div[@class='textArea']
selenium=//span[contains(text(),'Selenium')]/ancestor::ul/following-sibling::div//div[@class='textArea']
relocate=//span[contains(text(),'willing to relocate')]/ancestor::ul/following-sibling::div//input[@value='Yes']
testing=//span[contains(text(),'testing')]/ancestor::ul/following-sibling::div//div[@class='textArea']
current=//span[contains(text(),'current salary')]/ancestor::ul/following-sibling::div//div[@class='textArea']
expected=//span[contains(text(),'expected')]/ancestor::ul/following-sibling::div//div[@class='textArea']
experience=//span[contains(text(),'experience')]/ancestor::ul/following-sibling::div//div[@class='textArea']
