# Naukri login configuration
nokri_base.url=https://www.naukri.com/
naukri.user=shivamparashar1213@gmail.com
naukri.password=shivam1213

linkedin_base.url=https://www.linkedin.com/
linkedin.user=shivamparashar1213@gmail.com
linkedin.password=Shivam@1213
